## Axis

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([[1, 1.5, 'a', 17]]*100)

In [4]:
df

    0    1  2   3
0   1  1.5  a  17
1   1  1.5  a  17
2   1  1.5  a  17
3   1  1.5  a  17
4   1  1.5  a  17
5   1  1.5  a  17
6   1  1.5  a  17
7   1  1.5  a  17
8   1  1.5  a  17
9   1  1.5  a  17
10  1  1.5  a  17
11  1  1.5  a  17
12  1  1.5  a  17
13  1  1.5  a  17
14  1  1.5  a  17
15  1  1.5  a  17
16  1  1.5  a  17
17  1  1.5  a  17
18  1  1.5  a  17
19  1  1.5  a  17
20  1  1.5  a  17
21  1  1.5  a  17
22  1  1.5  a  17
23  1  1.5  a  17
24  1  1.5  a  17
25  1  1.5  a  17
26  1  1.5  a  17
27  1  1.5  a  17
28  1  1.5  a  17
29  1  1.5  a  17
.. ..  ... ..  ..
70  1  1.5  a  17
71  1  1.5  a  17
72  1  1.5  a  17
73  1  1.5  a  17
74  1  1.5  a  17
75  1  1.5  a  17
76  1  1.5  a  17
77  1  1.5  a  17
78  1  1.5  a  17
79  1  1.5  a  17
80  1  1.5  a  17
81  1  1.5  a  17
82  1  1.5  a  17
83  1  1.5  a  17
84  1  1.5  a  17
85  1  1.5  a  17
86  1  1.5  a  17
87  1  1.5  a  17
88  1  1.5  a  17
89  1  1.5  a  17
90  1  1.5  a  17
91  1  1.5  a  17
92  1  1.5  a  17
93  1  1.5  a  17
94  1  1.5  a  17
95  1  1.5  a  17
96  1  1.5  a  17
97  1  1.5  a  17
98  1  1.5  a  17
99  1  1.5  a  17

[100 rows x 4 columns]

In [5]:
df.dtypes

0      int64
1    float64
2     object
3      int64
dtype: object

In [6]:
df.mean()

0     1.0
1     1.5
3    17.0
dtype: float64

In [7]:
df.mean(axis=1)

0     6.5
1     6.5
2     6.5
3     6.5
4     6.5
5     6.5
6     6.5
7     6.5
8     6.5
9     6.5
10    6.5
11    6.5
12    6.5
13    6.5
14    6.5
15    6.5
16    6.5
17    6.5
18    6.5
19    6.5
20    6.5
21    6.5
22    6.5
23    6.5
24    6.5
25    6.5
26    6.5
27    6.5
28    6.5
29    6.5
     ...
70    6.5
71    6.5
72    6.5
73    6.5
74    6.5
75    6.5
76    6.5
77    6.5
78    6.5
79    6.5
80    6.5
81    6.5
82    6.5
83    6.5
84    6.5
85    6.5
86    6.5
87    6.5
88    6.5
89    6.5
90    6.5
91    6.5
92    6.5
93    6.5
94    6.5
95    6.5
96    6.5
97    6.5
98    6.5
99    6.5
Length: 100, dtype: float64

In [8]:
#?
df.transpose().mean() == df.mean(axis=1)

ValueError: Can only compare identically-labeled Series objects

In [ ]:
df.transpose().mean()

In [ ]:
df.transpose().dtypes